### PR TITLE
Fix docblock typos in JwtAuthEvents.php.

### PR DESCRIPTION
**Pull request by edwardchan**
Fixes some minor spelling errors in the docblocks.

### CODE REVIEW

**Comment by gabesullice** [comment]
Thanks!

**Comment by gabesullice** [comment]
If you have a drupal.org name, lmk so I can give you commit credit

**Comment by edwardchan** [comment]
@gabesullice Yup, it's edwardchiapet.

**Comment by edwardchan** [comment]
I also created issues in the JWT issue queue so it can be tracked. Thanks again :)

**Pull request merged**
